food_labels = ['apple', 'apple pie', 'apricot', 'avocado', 'avocado salad',
          'bagel', 'bagel sandwich', 'baguette bread', 'barley bread',
          'beef jerky', 'beer', 'bell pepper', 'black coffee', 'black tea',
          'blueberry', 'boiled egg', 'boiled pork wraps', 'brazil nut', 'bread',
          'broccoli', 'buckwheat', 'butter', 'cabbage salad', 'caesar salad',
          'cake', 'california roll', 'camembert cheese', 'canapé', 'cappuccino',
          'caprese salad', 'caramel', 'carbonara', 'carbonated drink', 'celery',
          'cereal bar', 'cheese', 'cherry', 'cherry tomato', 'chestnut', 'chewing gum',
          'chicken', 'chicken breast', 'chicken breast salad', 'chicken caesar salad',
          'chicken nuggets', 'chicken wings', 'chili pepper', 'chocolate ice cream',
          'chocolate muffin', 'cockle', 'cocoa', 'cold noodles', 'combination pizza',
          'cookie', 'cotton candy', 'cracker', 'cranberry', 'cream cheese', 'crepes',
          'croissant', 'cucumber', 'curry rice', 'curry sauce', 'dark chocolate', 'dim sum',
          'donut', 'doria', 'draft beer', 'dried plum', 'dried seaweed', 'egg', 'egg fried rice',
          'egg tart', 'eggplant', 'fresh fruit juice', 'fried chicken', 'fried egg', 'fried potatoes',
          'fried rice', 'fruit and vegetable salad', 'ginseng chicken soup', 'gorgonzola',
          'granny smith apple', 'grape', 'grapefruit', 'gratin', 'green bell pepper',
          'green grapes', 'green onion', 'grilled beef', 'grilled chicken breast',
          'grilled fish', 'grilled pork', 'grilled pork belly', 'grilled ribs',
          'grilled salmon', 'grilled sausage', 'grilled shrimp', 'guava',
          'ham and cheese sandwich', 'hamburger steak', 'honey', 'hot cake',
          'hot chocolate', 'hot sauce', 'hot wings', 'iced latte', 'jalapeno',
          'jelly', 'juice', 'jujube', 'kale', 'ketchup', 'kimbap', 'kimchi fried rice',
          'kiwi', 'kohlrabi', 'lamb skewers', 'lasagna', 'latte', 'lemonade',
          'lettuce salad', 'macaron', 'madeleine', 'maki rolls', 'mashed potato',
          'maté tea', 'mayonnaise', 'milk', 'miso soup', 'mocha with whipped cream',
          'muesli', 'muffin', 'mulberry', 'oatmeal', 'omelette', 'omurice', 'onion',
          'onion salad', 'orange', 'orange juice', 'oven-roasted chicken breast',
          'panini', 'papaya', 'passion fruit', 'pasta', 'peach', 'peanut butter',
          'pepper', 'pepperoni pizza', 'persimmon', 'pickled cabbage', 'pickled cucumber',
          "pig's feet", 'pineapple', 'pizza', 'popcorn', 'pork belly', 'pork ribs',
          'pork steak', 'porridge', 'potato chips', 'potato salad', 'pretzel', 'pudding',
          'pumpkin seeds', 'radish', 'raisins', 'ramen', 'red bean bread', 'red bell pepper',
          'red cabbage', 'red pepper powder', 'rice', 'rice cake', 'rice noodles', 'ricotta cheese',
          'risotto', 'roasted chestnuts', 'roasted coffee beans', 'salmon salad', 'salmon sushi',
          'salsa sauce', 'salt', 'sashimi', 'sausage', 'shake', 'shiitake mushroom', 'shrimp tempura',
          'sirloin steak', 'smoked chicken', 'soup', 'soy milk', 'soy sauce', 'spaghetti',
          'spicy seafood noodle soup', 'spicy stir-fried chicken', 'spinach', 'spring rolls',
          'squid', 'steak', 'stew', 'stir-fried noodles', 'stir-fried rice noodles', 'stir-fried vegetables',
          'sunflower seeds', 'sushi', 'sweet potato', 'tangerine', 'tiramisu', 'toast', 'tomato juice',
          'tomyumgoong', 'udon', 'vegetable juice', 'waffle', 'walnut', 'watermelon', 'white wine',
          'whole chicken', 'whole wheat bread', 'wine', 'yangju', 'yellow bell pepper', 'zucchini']